name: jaguar_static_file
version: 0.5.2

authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

description: Static file handler for jaguar

dependencies:
  jaguar: ^0.6.5

dev_dependencies:
  http: '>=0.11.3+13 <0.12.0'
  path: '>=1.4.1 <1.5.0'
  test:

