name: jaguar_static_file
version: 0.5.5
description: Static file handler for jaguar
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_static_file
documentation:

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  jaguar: ^0.6.7

dev_dependencies:
  http: '>=0.11.3+13 <0.12.0'
  path: '>=1.4.1 <1.5.0'
  test:

