name: jaguar_static_file
version: 0.2.1

authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

description: Static file handler for jaguar

dependencies:
  jaguar: ">=0.2.6 <0.3.0"

